### ISSUE TITLE
Feature request: Token delimiter

### ISSUE THREAD

**Issue by Stock84-dev** [sharnoff/derive-syn-parse#1]
Instead of writing a structure that contains a token and storing it.
```rust
use syn::{Ident, Token, Type};
use derive_syn_parse::Parse;

#[derive(Parse)]
struct MyField {
    ident: Ident,
    colon_token: Token![:],
    ty: Type,
}
```
It could be written without it:
```rust
use syn::{Ident, Token, Type};
use derive_syn_parse::Parse;

#[derive(Parse)]
struct MyField {
    ident: Ident,
    #[delimiter(Token![:])] // Before parsing `ty` we parse provided token and discard it.
    ty: Type,
}
```

**Comment by sharnoff** [comment]
That's a cool idea - thanks for the suggestion :)

I feel like `#[delimiter(...)]` might imply a slightly different behavior -- what do you think about `#[prefix(...)]`? We could similarly have a corresponding `#[postfix(...)]`, for the case where someone wants to parse something at the end of the struct, e.g.:

```rust
#[derive(Parse)]
struct MyField {
    ident: Ident,
    #[prefix(Token![:])]
    #[postfix(Token![,])]
    ty: Type.
}
```
as equivalent to
```rust
#[derive(Parse)]
struct MyField {
    ident: Ident,
    colon: Token![:],
    ty: Type.
    comma: Token![,],
}
```

**Comment by Stock84-dev** [comment]
Haven't thought about that ;)
`prefix` and `postfix` is better.
We could also support multiple `prefix` and `postfix` attributes for the same field.
```rust
#[derive(Parse)]
struct MyField {
    ident: Ident,
    #[prefix(Token![while])]
    #[prefix(Token![in])]
    #[postfix(Token![do])]
    #[postfix(Token![+])]
    ty: Type
}
```

**Comment by sharnoff** [comment]
Yeah, that's true - haha. I think it would actually be simpler to support multiple `prefix`/`postfix` attributes for a single field by default (even though that may not be the most readable).

Something else is perhaps allowing `#[prefix(Foo as foo)]`, to allow referring to that field later - such as:
```rust
#[derive(Parse)]
struct myField {
    ident: Ident,
    #[prefix(Token![:])]
    ty: Type,

    #[prefix(Option<Token![=]> as eq_token)]
    #[parse_if(eq_token.is_some())]
    value: Option<Expr>,
}
```

This would parse something like
```
foo: Vec<Bar>
```
or
```
baz: i32 = 0
```

It's unambiguous if `#[prefix(..)]` has the form `#[prefix( <TYPE> ["as" IDENT] )]`, but if we had something like `#[prefix_with(..)]` to supply an arbitrary parsing function instead, that syntax would be *difficult*. That being said, IMO prefixing probably doesn't need to be full-featured so it's safe to assume that we don't need to plan for compatibility with a hypothetical `#[prefix_with]`.

I'll get started on an experimental implementation - shouldn't be too bad. Syntax is generally pretty easy to adjust :)

**Comment by sharnoff** [comment]
Just got an initial implementation going - let me know if you find any problems with it :)

(for reference, on adding github repos to your `Cargo.toml`, if you happen to be unfamiliar: [link](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)) 

I'll leave this isuse open until I add some documentation - going to wait to do a release until then as well.
