### ISSUE TITLE
Feature request: derive `quote::ToTokens`

### ISSUE THREAD

**Issue by bravely-beep** [sharnoff/derive-syn-parse#5]
This might be a bit ambitious, but it'd be very cool to be able to derive `quote::ToTokens` as a sort of inverse to deriving `syn::Parse`. Worth considering?

**Comment by sharnoff** [comment]
That's an interesting idea! I agree it definitely would be cool - I think given the name of this crate, it'd be a little strange to also provide a derive macro for `ToTokens`, but I'd be happy to make a companion library along the lines of `derive-quote-totokens` if there's interest.

Another option would be to change the name of this crate (which in general I'm open to), but I can't think of any crate names that would be similarly searchable.

**Comment by bravely-beep** [comment]
For what it's worth, since I posted that I've discovered https://crates.io/crates/parsel which has a `ToTokens` derive, so it might not be worth reimplementing that again 😅

**Comment by sharnoff** [comment]
Ah nice! That seems like a really cool library - it looks like enum parsing _may_ be worst-case exponential, but in practice should be fine. And yeah, probably not worth reimplementing that haha
