### ISSUE TITLE
`syn` v2.0

### ISSUE THREAD

**Issue by s-arash** [sharnoff/derive-syn-parse#7]
`syn` has released a [v2](https://github.com/dtolnay/syn/releases/tag/2.0.0). Are there plans to move to `syn` v2?

This crate has been really helpful to me in defining custom syntax in my [Ascent](https://github.com/s-arash/ascent/) library, and it'd be great if I could continue relying on `derive-syn-parse` as I transition to the new version of `syn`.

**Comment by sam0x17** [comment]
Yeah I will probably need to fork soon if it doesn't get updated :/

**Comment by racharron** [comment]
I've made a fork that uses `syn` v2.  Note that I am unfamiliar with the codebase, syn, and proc macros in general, so I'd prefer it if someone looked over my fork before I made a pull request since I mostly just tried to fix compilation errors and then test failures.
At this point, my fork passes all (non-doc) tests, but I don't know if there are any blind spots that I'm missing or if there are any other libraries I should test with this version.

**Comment by sam0x17** [comment]
@racharron if you put up a pull request I can take a look and try to review it. If @sharnoff has truly abandoned this we can set up a fork but might as well try with a PR first 👍🏻

**Comment by sharnoff** [comment]
Hey, so sorry for taking so long to reply here. Been quite swamped with work.

Thank you for opening a PR @racharron — otoh, I see no issues with it. Will try to give a thorough review & hopefully can publish a new release asap.

Longer-term, I would love to hand off ownership of this crate to someone else, if there's any any interest in maintaining it.

At the same time, this library is quite small; if there's no need for significant future changes, perhaps the maintenance burden is low enough to be manageable.

**Comment by racharron** [comment]
It all looks good to me.
Unfortunately, I do not have the time to take ownership* of this crate at the moment.  Maybe in a few months after I graduate and get a job?

\* The real issue would be taking the time to actually understand the crate, as opposed the the basically blind "fix the compile errors then fix the test errors" thing that I did.  I'd have to learn how to use `syn` too, which is something I really don't know at the moment, nor do I really have any time nor inclination at the moment to learn.

**Comment by sam0x17** [comment]
I could probably take this over if you want @sharnoff, though I'd need a better understanding of the test setup and whether the current CI is actually checking everything. I know syn quite well, and already maintain a bunch of crates that use a lot of syn stuff like `macro_magic`, `docify`, etc.

Perhaps we could cut this release first though? I know a lot of builds would be faster if they didn't have to build 1.x and 2.x syn, and this is a dep in thousands of crates

**Comment by sharnoff** [comment]
v0.2.0 [has now been released](https://docs.rs/derive-syn-parse/0.2.0/derive_syn_parse/index.html). I've tested upgrading in the following crates:

- `s-arash/ascent` (requires enabling the `full` feature to parse a closure, haven't looked into why it wasn't needed before)
- `sam0x17/macro_magic` (no other changes required AFAICT, although I did have a single test failing both before & after)
- `sam0x17/docify` (no other changes required)

Please let me know how it goes. To be plainly honest, this repo does not have sufficient testing — if there's issues, I'm more than happy to yank & re-release with fixes.

And once again, my sincere apologies for taking so long.
@sam0x17 I'll email you to sort out details.

**Comment by s-arash** [comment]
@sharnoff @racharron Thanks for the great work! It's really appreciated.
